theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - docs/GenericUtterances.md
  - docs/UtteranceExtensions.md
  - docs/Train.md
  - docs/Test.md
  - docs/Clean.md
  - docs/Analyze.md
  - docs/LuisModelConfiguration.md
  - docs/LuisEndpointConfiguration.md
  - docs/LexModelConfiguration.md
  - docs/LexEndpointConfiguration.md
  - docs/DialogflowEndpointConfiguration.md
  - docs/AzurePipelines.md
  - docs/CliExtensions.md
  - docs/NLUTrainTask.md
  - docs/NLUTestTask.md
  - docs/NLUCleanTask.md
  - docs/examples/metadata.json
  - docs/examples/statistics.json
  - extensions/overview.md
